src/main/java/br/com/tophat/managedbean/ChatMB.java
package br.com.tophat.managedbean;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

import org.primefaces.context.RequestContext;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@ManagedBean(name="chatMB")
@ViewScoped
public class ChatMB {

	private Logger logger = LoggerFactory.getLogger(ChatMB.class);
	
	private String message;

	/**
	 * URL raiz do websocket
	 */
	private static final String WEBSOCKET_URL = "ws://ws-chat.vueda.cloudbees.net/chat/";
	//private static final String WEBSOCKET_URL = "ws://localhost:8080/ws-chat/chat/";
	
	public String getUrl(){
		return WEBSOCKET_URL;
	}

	public String getMessage() {
		return message;
	}

	public void setMessage(String message) {
		this.message = message;
	}
	
	
	
}

src/main/webapp/index.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui">

<h:head>
	<link rel="stylesheet" type="text/css" href="styles.css" />
	<title>WS CHAT</title>
</h:head>
<h:body>
	<script type="text/javascript">
		var wsSocket;
		
		function connect() {
			var wsUrl = '${chatMB.url}';
			var room = document.getElementById('connectForm:roomSelector').innerText;		
			var username = document.getElementById('connectForm:username').value;
			if(username){
				if(room){
					wsSocket = new WebSocket(wsUrl + room + '/' + username);
						
					wsSocket.onmessage = function(msg){
						$("#messages").append(msg.data + '<br></br>');				
					}
						
					wsSocket.onerror = function(){
						$("#messages").append('Erro ao conectar' + '<br></br>');								
					}
				}
			}
		}
		
		function send(){
			var newMessage = document.getElementById('indexForm:newMessage');
			wsSocket.send(newMessage.value);
			newMessage.value = '';
		}
	</script>
	
	<p:menubar styleClass="menuBar">
		<f:facet name="options">
			<p:commandButton onclick="connectDialog.show()" type="button"
				styleClass="ui-priority-primary" value="Conectar"
				icon="ui-icon-person" />
		</f:facet>
	</p:menubar>

	<p:dialog id="dialog" header="Conectar" widgetVar="connectDialog"
		resizable="false">
		<h:form id="connectForm">
			<p:growl id="growl" showDetail="true" life="3000" />

			<h:panelGrid columns="2" cellpadding="5">
				<h:outputLabel for="username" value="Nome:" />
				<p:inputText label="Nome" id="username"
					required="true" requiredMessage="É necessário informar um nome">
				</p:inputText>

				<p:selectOneMenu label="Sala" id="roomSelector" required="true"
					requiredMessage="É necessário selecionar uma sala">
					<f:selectItem itemLabel="Selecione um item" itemValue="" />
					<f:selectItem itemLabel="Comptus" itemValue="comptus" />
					<f:selectItem itemLabel="LOL" itemValue="lol" />
				</p:selectOneMenu>

				<f:facet name="footer">
					<p:commandButton id="connect" value="Conectar" onclick="connect()"
						onsuccess="connectDialog.hide();" styleClass="ui-priority-primary"
						update="connectForm :indexForm growl" />
				</f:facet>
			</h:panelGrid>
		</h:form>
	</p:dialog>

	<h:form id="indexForm">
		<p:panel id="messagesPanel">
			<p:scrollPanel id="scrollableMessages" style="height:500px" mode="native">
				<div id="messages"></div>
			</p:scrollPanel>
			<p:panelGrid>
				<p:row>
					<p:column styleClass="inputMessageColumn">
						<p:inputText  styleClass="inputMessageField"
							placeholder="Digite a mensagem" id="newMessage"
							value="#{chatMB.message}" disabled="false" />
					</p:column>
					<p:column style="border:none">
						<p:commandButton id="sendMessage" value="Enviar"
							icon="ui-icon-mail-closed" onclick="send()"
							disabled="false" />
					</p:column>
				</p:row>
			</p:panelGrid>
		</p:panel>
	</h:form>
</h:body>
</html>